# Site settings
title: 李二狗的博客
bigTitle: 程序小刀的学习之道
SEOTitle: 李二狗的博客 | Srefan Blog
header-img: img/home-bg.jpg
email: liyangkobebryant@gmail.com
description: "生活不止眼前的苟且, 还有远方的 Hello World!"
keyword: "李二狗, 李二狗的技术博客, Srefan, srefan, @Srefan, @srefan, yangbryant, Blog, 博客, 个人网站, 嵌入式, 互联网, C/C++, Objective-C, Web, JavaScript, Node.js, Go, Python, iOS, 前端, 后端, 设计"
url: "https://blog.srefan.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

author: Srefan

# SNS settings
RSS: false
# weibo_username:     srefan
zhihu_username:     yangbryant
github_username:    yangbryant
#twitter_username:   id
#facebook_username:  id
#linkedin_username:  firstname-lastname-idxxxx
resumeurl: "https://resume.srefan.com"

cover_color: lightgray
page-img: img/page-bg.jpg

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:year/:month/:title/
# permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: srefan


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'your track id'            # Format: UA-xxxxxx-xx
# ga_domain: [your domain]



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Keep on going, Never give up!<br>犹犹豫豫豫豫犹, 人生何处是尽头"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
# friends: [
    # {
    #     title: "乱序",
    #     href: "http://mida.re/"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # }
# ]
