 # Basic
header_title: 程序小刀的学习之道
title: Srefan
subtitle: 生活不止眼前的苟且
welcome_message: <a href="https://github.com/yangbryant/yangbryant.github.io" target="_blank">我为你创造了世界,</br>但你依然沉睡在你仅有的梦中...</br></br>/* Keep on going never give up */</a>
description: print ( "Hello World !" )
creator: <a href="https://github.com/yangbryant">@Srefan</a>

url: "http://yangbryant.github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'https://github.com/yangbryant'}
    - {title: 关于, description: 关于我, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: 
    - jekyll-redirect-from
    - jekyll-paginate

paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    duoshuo: srefan
    
# Social
social:
    weibo: srefan
    github: yangbryant
    jianshu: 5b71fccf2255
    skype: liyangkobeci
    mail: liyangkobebryant@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

#donate
reward: true
